project: 
  type:  website
  render:
    - index.qmd
    - semana1.qmd
    - ex1.qmd
    - semana2.qmd
    - 03_inverse.qmd
    - 04_determinant.qmd
    - 05_vetores.qmd
    

render-on-save: false 

execute:
  freeze: true

title: "Geometria Analítica e Álgebra Linear"
subtitle: Apostilas
author:
  - name: "Csaba Schneider"
    affiliation: Universidade Federal de Minas Gerais
date: "Criado e atualizado 2025/II"

# license: "n/a"
# copyright:
#  holder: Csaba Schneider
#   year: 2025

format:
  revealjs:
    css: styles.css
    #width: 2000 # 16:9 
    #height: 9000 
    margin: 0.00 # less edge padding 
    # minScale: 0.2 
    # maxScale: 2.0 
    # theme: simple
    # scroll: true
  html:
    css: article.css
    include-after-body:
      - text: |
          <script>
          window.MathJax = window.MathJax || {};
          </script>
          <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>
  pdf: 
    include-in-header:
     - file: macros.tex
  beamer: 
    include-in-header:
     - file: macros.tex
