project: 
  type: website 
  render:
    - index.qmd
    - semana1.qmd
    - ex1.qmd
    - semana2.qmd

render-on-save: false 

execute:
  freeze: true

title: "Geometria Analítica e Álgebra Linear"
subtitle: Apostilas
author:
  - name: "Csaba Schneider"
    affiliation: Universidade Federal de Minas Gerais
date: "Criado e atualizado 2025/II"

# license: "n/a"
# copyright:
#  holder: Csaba Schneider
#   year: 2025

format:
  revealjs:
    css: styles.css
  html:
    css: article.css

