project: 
  type: website 
  render:
    - index.qmd
    - semana1.qmd
    - ex1.qmd
    - semana2.qmd

render-on-save: false 

execute:
  freeze: true

title: "Geometria Analítica e Álgebra Linear"
subtitle: Apostilas
author:
  - name: "Csaba Schneider"
    affiliation: Universidade Federal de Minas Gerais
date: "Criado e atualizado 2025/II"

# license: "n/a"
# copyright:
#  holder: Csaba Schneider
#   year: 2025

format:
  revealjs:
    css: styles.css
    width: 1024 # add this in init or config
    height: 768
    # width: 1920 # 16:9 
    # height: 1080 
    margin: 0.02 # less edge padding 
    minScale: 0.2 
    maxScale: 2.0 
    center: false # optional: reduces top whitespace
    include-in-header: macros.html
  html:
    css: article.css
    include-in-header:
     - file: macros.html

